---
title: "Demographics_16.1.2024"
author: "Johanna M Groening"
date: "2024-01-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stringr)
```


```{r}
str(df_demographics_combined)
```


```{r}
summary(df_demographics_combined)
```


```{r}
class(df_demographics_combined)
```
```{r}
df_demographics_clean <- as_tibble(df_demographics_combined)

head(df_demographics_combined)
```

```{r}
head(df_demographics_clean)
```


```{r}
df_demographics_clean$country <- ifelse(!is.na(df_demographics_clean$country.text),
                                        df_demographics_clean$country.text,
                                        df_demographics_clean$country.1)

df_demographics_clean$country <- paste(df_demographics_clean$country.text, 
                                       df_demographics_clean$country.1, 
                                        collapse = NULL)
df_demographics_clean$country
```

```{r}
class(df_demographics_clean)
```

```{r}
df_demographics_clean$country <- as.factor(df_demographics_clean$country)
levels(df_demographics_clean$country)
```

```{r}
df_demographics_clean$country <- str_to_title(df_demographics_clean$country) 
levels(df_demographics_clean$country)
```

```{r}

df_demographics_clean$country  <- as.factor(str_to_title(trimws(gsub("\\s+", " ", df_demographics_clean$country))))

print(df_demographics_clean$country)
levels(df_demographics_clean$country)
```

```{r}
df_demographics_clean$country <-gsub("Na United Kingdom", "United Kingdom",df_demographics_clean$country)
df_demographics_clean$country <-gsub("U.s.a", "USA",df_demographics_clean$country)
df_demographics_clean$country <-gsub("United States", "USA",df_demographics_clean$country)
df_demographics_clean$country <-gsub("USA.", "USA",df_demographics_clean$country)
df_demographics_clean$country <-gsub("Usa", "USA",df_demographics_clean$country)
df_demographics_clean$country <-gsub("Na Na", "Na",df_demographics_clean$country)
df_demographics_clean$country <-gsub("Nl", "Netherlands",df_demographics_clean$country)
```

```{r}
df_demographics_clean$country <- as.factor(df_demographics_clean$country)
print(levels(df_demographics_clean$country))
```

```{r}
table(df_demographics_clean$country)

barplot(table(df_demographics_clean$country))
```

```{r}

#here I made a new variable based on the timezones that I found on the internet
df_demographics_clean <- df_demographics_clean %>%
  mutate(Region = case_when(
    Local.Timezone == "1" ~ "Europe",
    Local.Timezone == "5.5" ~ "India",
    Local.Timezone == "-4" ~ "Canada/South America",
    Local.Timezone == "3" ~ "Kenya",
    Local.Timezone == "-2.5" ~ "Canada",
    Local.Timezone == "-5" ~ "USA (East)",
    Local.Timezone == "-6" ~ "USA (Central)",
    Local.Timezone == "2" ~ "Europe (East)",
    Local.Timezone == "-7" ~ "USA (Mountain)",
    Local.Timezone == "8" ~ "China",
    Local.Timezone == "-3" ~ "South America",
    Local.Timezone == "10" ~ "Australia",
    Local.Timezone == "7" ~ "South Asia",
    Local.Timezone == "0" ~ "UK",
    Local.Timezone == "-8" ~ "USA (Pacific)",
     Local.Timezone == "-10" ~  "Hawaii" ,
Local.Timezone == "6" ~ "Bangladesh",
Local.Timezone == "4" ~ "Arabia",
Local.Timezone == "11" ~  "Russia",
    TRUE ~ "Unknown"
  ))
print(df_demographics_clean$Region)

```

```{r}
kenya_data <- df_demographics_clean %>%
  filter(Local.Timezone == "3" )

print(kenya_data)
```


```{r}

# here I created a new dataframe without Kenya
without_kenya_df <- df_demographics_clean %>%
  filter(Region != "Kenya")

#I created a new dataframe with only Europe and UK
europe_uk_df <- df_demographics_clean %>%
  filter(Region %in% c("Europe", "UK"))
```

```{r}

write.csv(without_kenya_df, file.path( "without_kenya.csv"), row.names = FALSE)


write.csv(europe_uk_df, file.path("europe_uk.csv"), row.names = FALSE)
```

```{r}
names(without_kenya_df)
```
```{r}
table(without_kenya_df$branch.huc2)

barplot(table(without_kenya_df$branch.huc2))

```

```{r}
table(without_kenya_df$branch.b8n7)

barplot(table(without_kenya_df$branch.b8n7))
```

```{r}
table(without_kenya_df$branch.19ea)

barplot(table(without_kenya_df$branch.19ea))
```

```{r}
table(without_kenya_df$branch.huc2)

barplot(table(without_kenya_df$branch.huc2))

```



```{r}
table(df_demographics_clean$branch.b8n7)

barplot(table(df_demographics_clean$branch.b8n7))
```

```{r}
table(df_demographics_clean$branch.19ea)

barplot(table(df_demographics_clean$branch.19ea))
```
```{r}
table(df_demographics_clean$branch.huc2)

barplot(table(df_demographics_clean$branch.huc2))

```


```{r}
df_demographics_clean$Spacetaskdone <- gsub(" Space Task Done", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NA Space Task Done", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub(" ", "NA",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NASpace_Task_Done", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("Space_Task_DoneNA", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NASpace_Task_Done", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NANA", "NA",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NASpace_Task_Done", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("Space_task_DoneNA", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NASpace_task_Done", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NANANA", "NA",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NANA", "NA",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("SpaceNATaskNADoneNA", "Space_task_Done",df_demographics_clean$Spacetaskdone )

table(df_demographics_clean$Spacetaskdone)
print(df_demographics_clean$Spacetaskdone)
```


```{r}
df_demographics_clean$Spacetaskdone <- ifelse(!is.na(df_demographics_clean$checkpoint.l38h),
                                        df_demographics_clean$checkpoint.l38h,
                                        df_demographics_clean$checkpoint.zp1s)

# Concatenate values with a comma and space
df_demographics_clean$Spacetaskdone <- paste(df_demographics_clean$checkpoint.zp1s, 
                                       df_demographics_clean$checkpoint.l38h, 
                                        collapse = NULL)
table(df_demographics_clean$Spacetaskdone)
print(df_demographics_clean$Spacetaskdone)
```


```{r}
df_demographics_clean$Spacetaskdone <- gsub(" Space Task Done", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NA Space Task Done", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub(" ", "NA",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NASpace_Task_Done", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("Space_Task_DoneNA", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NASpace_Task_Done", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NANA", "NA",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NASpace_Task_Done", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("Space_task_DoneNA", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NASpace_task_Done", "Space_task_Done",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NANANA", "NA",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("NANA", "NA",df_demographics_clean$Spacetaskdone )
df_demographics_clean$Spacetaskdone <- gsub("SpaceNATaskNADoneNA", "Space_task_Done",df_demographics_clean$Spacetaskdone )

table(df_demographics_clean$Spacetaskdone)
print(df_demographics_clean$Spacetaskdone)
```

```{r}
df_demographics_clean$Socialtaskdone <- ifelse(!is.na(df_demographics_clean$checkpoint.zmw5),
                                        df_demographics_clean$checkpoint.zmw5,
                                        df_demographics_clean$checkpoint.oafw)

# Concatenate values with a comma and space
df_demographics_clean$Socialtaskdone <- paste(df_demographics_clean$checkpoint.oafw, 
                                       df_demographics_clean$checkpoint.zmw5, 
                                        collapse = NULL)
table(df_demographics_clean$Socialtaskdone)
print(df_demographics_clean$Socialtaskdone)

```

```{r}
df_demographics_clean$Socialtaskdone <- gsub(" Social Task Done", "Social_task_Done",df_demographics_clean$Socialtaskdone )
df_demographics_clean$Socialtaskdone <- gsub("NA Social Task Done", "Social_task_Done",df_demographics_clean$Socialtaskdone )
df_demographics_clean$Socialtaskdone <- gsub(" ", "NA",df_demographics_clean$Socialtaskdone )
df_demographics_clean$Socialtaskdone <- gsub("NASocial_Task_Done", "Social_task_Done",df_demographics_clean$Socialtaskdone )
df_demographics_clean$Socialtaskdone <- gsub("Social_Task_DoneNA", "Social_task_Done",df_demographics_clean$Socialtaskdone )
df_demographics_clean$Socialtaskdone <- gsub("NASocial_Task_DoneNANA", "Social_task_Done",df_demographics_clean$Socialtaskdone )
df_demographics_clean$Socialtaskdone <- gsub("NANA", "NA",df_demographics_clean$Socialtaskdone )
df_demographics_clean$Socialtaskdone <- gsub("NASocial_Task_Done", "Social_task_Done",df_demographics_clean$Socialtaskdone )
df_demographics_clean$Socialtaskdone <- gsub("Social_task_DoneNA", "Social_task_Done",df_demographics_clean$Socialtaskdone )
df_demographics_clean$Socialtaskdone <- gsub("NASocial_task_Done", "Social_task_Done",df_demographics_clean$Socialtaskdone )

table(df_demographics_clean$Socialtaskdone)
print(df_demographics_clean$Socialtaskdone)
```

```{r}
without_kenya_df <- df_demographics_clean %>%
  filter(Region != "Kenya")

table(without_kenya_df$Socialtaskdone)
table(without_kenya_df$Spacetaskdone)
```

```{r}
write_csv(without_kenya_df,"df_excluding_kenyians")
```

```{r}
ls()
```

